# How the image is parse, in order to get the colors:
# full - resized - wal - thumb -  fastresize - kmeans
backend = "wal"

# What color space to use to produce and select the most prominent colors:
# lab - labmixed - lch - lchmixed
color_space = "lch"

# Use the most prominent colors in a way that makes sense, a scheme color palette:
# dark - dark16 - darkcomp - darkcomp16
# light - light16 - lightcomp - lightcomp16
# harddark - harddark16 - harddarkcomp - harddarkcomp16
# softdark - softdark16 - softdarkcomp - softdarkcomp16
# softlight - softlight16 - softlightcomp - softlightcomp16
palette = "dark"


[templates]
# NOTE: prefer '' over "" for paths, avoids escaping.
# template: A RELATIVE path that points to `~/.config/wallust/template` (depends on platform)
# target: ABSOLUTE path in which to place a file with generated templated values.
# ยก If either one is a directory, then both SHOULD be one. !
# zathura = { template = 'zathura', target = '~/.config/zathura/zathurarc' }

# hypr = { src = 'hyprland.conf', dst = '~/.config/hypr/conf/border.conf' }
#
waybar = { src = 'waybar.css', dst = '~/.config/waybar/colors.css' }
#
wlogout = { src = 'wlogout.css', dst = '~/.config/wlogout/colors.css' }
#
# gtk3 = { src = 'gtk.css', dst = '~/.config/gtk-3.0/colors.css' }
# #
# gtk4 = { src = 'gtk.css', dst = '~/.config/gtk-4.0/colors.css' }
#
# mako = {src = 'makoconfig', dst = '~/.config/mako/config' }
tmux = {src = 'tmux-colors.conf', dst = '~/.config/tmux/colors.conf' }

# ghostty_blaze = {src = 'ghostty_blaze_shader.glsl', dst = '~/.config/ghostty/shaders/cursor_blaze.glsl'}
